workflows:
  meu-novo-build:
    name: Compilar APK Android Moderno
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Limpar e criar estrutura nativa limpa
        script: |
          flutter clean
          flutter create . --org com.mapaterritorio.app --platforms android
      - name: Instalar dependências
        script: |
          flutter pub get
      - name: Construir APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  
