
  workflows:
  meu-primeiro-workflow: # ID do seu workflow
    name: Build de Produção
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Instalar dependências
        script: npm install
      - name: Executar testes
        script: npm test
