workflows:
  flutter-android-workflow:
    name: Compilar APK Android
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Criar estrutura nativa e dependências
        script: |
          flutter create . --org com.mapaterritorio.app --platforms android
          flutter pub get
      - name: Construir APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  
